### PR TITLE
Ot222 24 - Login Form

### PR DESCRIPTION
**Pull request by jero237**
- Login form created at components/LoginForm.jsx with using Formik for validation.

### CODE REVIEW

**Comment by LucasSequeDev** [comment]
Jero, valida si el regex esta correcto. Que pasaria en un mail lucas@memail.online ??

**Comment by jero237** [comment]
## What?
Component styled using Chakra UI.
## Why?
To match Figma's UX model.
## How?
First I've replaced HTML's button and input for Chakra's ones (dd23fd3).
Then I created variants for those elements using Chakra's custom theming system (3bffbaf), imported Poppins font (f008fe7) and modularized already existing theme (8beee7c).
## Screenshots
Result:
image
## Anything Else?
I've also updated react-redux to match react 18 (d699de3), and reverted two previous commits made by mistake (7cea246 and 83afeb6).

**Comment by LucasSequeDev** [comment]
Hola @jero237 falta agregar el componente a la ruta `/login`

**Comment by jero237** [comment]
Listo
### Mobile:
screencapture-localhost-3000-login-2022-06-27-22_11_47
### PC:
screencapture-localhost-3000-login-2022-06-27-22_11_25

**Pull request merged**
